export const ICON_TYPE = {
  SOLID: 'fas',
  REGULAR: 'far',
  BRAND: 'fab'
};

export const ICON_NAME = {
  REG_SOLID: {
    ADDRESS_BOOK: 'address-book',
    ADDRESS_CARD: 'address-card',
    ENVELOPE: 'envelope',
    ENVELOPE_OPEN: 'envelope-open',
    EYE: 'eye',
    EYE_SLASH: 'eye-slash',
    ID_CARD: 'id-card',
    ID_BADGE: 'id-badge',
    IMAGE: 'image',
    FILE: 'file',
    CREDIT_CARD: 'credit-card',
    EDIT: 'edit',
    USER: 'user',
    CALENDAR: 'calendar',
    PAPER_PLANE: 'paper-plane'
  },
  SOLID: {
    LINK: 'link',
    LOCK: 'lock',
    LOCK_OPEN: 'lock-open',
    BIRTHDAY_CAKE: 'birthday-cake',
    BITCOIN_SIGN: 'bitcoin-sign',
    RUPEE: 'rupee',
    RUPEE_SIGN: 'rupee-sign',
    DOLLAR: 'dollar',
    DOLLAR_SIGN: 'dollar-sign',
    EURO_SIGN: 'euro-sign',
    EXCLAMATION: 'exclamation',
    EXCLAMATION_CIRCLE: 'exclamation-circle',
    EXCLAMATION_TRIANGLE: 'exclamation-triangle',
    SEARCH: 'search',
    PEN: 'pen',
    PEN_NIB: 'pen-nib',
    PHONE: 'phone'
  },
  BRAND: {
    AMAZON_PAY: 'amazon-pay',
    ANGULAR: 'angular',
    ANDROID: 'android',
    GOOGLE_PLAY: 'google-play',
    APPLE: 'apple',
    APP_STORE: 'app-store',
    TWITTER: 'twitter',
    FACEBOOK: 'facebook',
    WHATSAPP: 'whatsapp',
    TELEGRAM: 'telegram',
    GITHUB: 'github',
    STACK_OVERFLOW: 'stack-overflow',
    YOUTUBE: 'youtube',
    G_PAY: 'google-pay',
    PAYPAL: 'paypal',
    CC_PAYPAL: 'cc-paypal',
    STRIPE: 'stripe',
    APPLE_PAY: 'apple-pay',
    BITCOIN: 'bitcoin',
    CHROME: 'chrome',
    DISCORD: 'discord',
    INSTA: 'instagram',
    LINKED_IN: 'linkedin',
    SKYPE: 'skype',
    SLACK: 'slack'
  }
};